window.esdocSearchIndex = [
  [
    "gcs/js/constants/buttontypes.js~button",
    "variable/index.html#static-variable-BUTTON",
    "<span>BUTTON</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~checkbox",
    "variable/index.html#static-variable-CHECKBOX",
    "<span>CHECKBOX</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~critical_button",
    "variable/index.html#static-variable-CRITICAL_BUTTON",
    "<span>CRITICAL_BUTTON</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/calibrationstore.js~calibrationstore",
    "class/js/stores/CalibrationStore.js~CalibrationStore.html",
    "<span>CalibrationStore</span> <span class=\"search-result-import-path\">GCS/js/stores/CalibrationStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~calibrationtypes",
    "variable/index.html#static-variable-CalibrationTypes",
    "<span>CalibrationTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~datetime",
    "variable/index.html#static-variable-DATETIME",
    "<span>DATETIME</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~dropdown",
    "variable/index.html#static-variable-DROPDOWN",
    "<span>DROPDOWN</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~file_input",
    "variable/index.html#static-variable-FILE_INPUT",
    "<span>FILE_INPUT</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/fencestore.js~fencestore",
    "class/js/stores/FenceStore.js~FenceStore.html",
    "<span>FenceStore</span> <span class=\"search-result-import-path\">GCS/js/stores/FenceStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~fencetypes",
    "variable/index.html#static-variable-FenceTypes",
    "<span>FenceTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/frequency.js~interop_receive_frequency",
    "variable/index.html#static-variable-INTEROP_RECEIVE_FREQUENCY",
    "<span>INTEROP_RECEIVE_FREQUENCY</span> <span class=\"search-result-import-path\">GCS/js/constants/Frequency.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/interopstore.js~interopstore",
    "class/js/stores/InteropStore.js~InteropStore.html",
    "<span>InteropStore</span> <span class=\"search-result-import-path\">GCS/js/stores/InteropStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~interoptypes",
    "variable/index.html#static-variable-InteropTypes",
    "<span>InteropTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/actiontypes.js~maptypes",
    "variable/index.html#static-variable-MapTypes",
    "<span>MapTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/frequency.js~plane_receive_frequency",
    "variable/index.html#static-variable-PLANE_RECEIVE_FREQUENCY",
    "<span>PLANE_RECEIVE_FREQUENCY</span> <span class=\"search-result-import-path\">GCS/js/constants/Frequency.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/parametersstore.js~parametersstore",
    "class/js/stores/ParametersStore.js~ParametersStore.html",
    "<span>ParametersStore</span> <span class=\"search-result-import-path\">GCS/js/stores/ParametersStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~parameterstypes",
    "variable/index.html#static-variable-ParametersTypes",
    "<span>ParametersTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/sdastore.js~sdastore",
    "class/js/stores/SdaStore.js~SdaStore.html",
    "<span>SdaStore</span> <span class=\"search-result-import-path\">GCS/js/stores/SdaStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~sdatypes",
    "variable/index.html#static-variable-SdaTypes",
    "<span>SdaTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/settingsstore.js~settingsstore",
    "class/js/stores/SettingsStore.js~SettingsStore.html",
    "<span>SettingsStore</span> <span class=\"search-result-import-path\">GCS/js/stores/SettingsStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~settingstypes",
    "variable/index.html#static-variable-SettingsTypes",
    "<span>SettingsTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/statusstore.js~statusstore",
    "class/js/stores/StatusStore.js~StatusStore.html",
    "<span>StatusStore</span> <span class=\"search-result-import-path\">GCS/js/stores/StatusStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~statustypes",
    "variable/index.html#static-variable-StatusTypes",
    "<span>StatusTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/store.js~store",
    "class/js/stores/Store.js~Store.html",
    "<span>Store</span> <span class=\"search-result-import-path\">GCS/js/stores/Store.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/buttontypes.js~text",
    "variable/index.html#static-variable-TEXT",
    "<span>TEXT</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~text_button",
    "variable/index.html#static-variable-TEXT_BUTTON",
    "<span>TEXT_BUTTON</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~text_input",
    "variable/index.html#static-variable-TEXT_INPUT",
    "<span>TEXT_INPUT</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/buttontypes.js~text_lock",
    "variable/index.html#static-variable-TEXT_LOCK",
    "<span>TEXT_LOCK</span> <span class=\"search-result-import-path\">GCS/js/constants/ButtonTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/tuningstore.js~tuningstore",
    "class/js/stores/TuningStore.js~TuningStore.html",
    "<span>TuningStore</span> <span class=\"search-result-import-path\">GCS/js/stores/TuningStore.js</span>",
    "class"
  ],
  [
    "gcs/js/constants/actiontypes.js~tuningtypes",
    "variable/index.html#static-variable-TuningTypes",
    "<span>TuningTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/stores/waypointstore.js~waypointstore",
    "variable/index.html#static-variable-WaypointStore",
    "<span>WaypointStore</span> <span class=\"search-result-import-path\">GCS/js/stores/WaypointStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/actiontypes.js~waypointtypes",
    "variable/index.html#static-variable-WaypointTypes",
    "<span>WaypointTypes</span> <span class=\"search-result-import-path\">GCS/js/constants/ActionTypes.js</span>",
    "variable"
  ],
  [
    "gcs/js/actions/calibrationactioncreator.js~addcalibrationline",
    "function/index.html#static-function-addCalibrationLine",
    "<span>addCalibrationLine</span> <span class=\"search-result-import-path\">GCS/js/actions/CalibrationActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~addlocation",
    "function/index.html#static-function-addLocation",
    "<span>addLocation</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~addwaypoint",
    "function/index.html#static-function-addWaypoint",
    "<span>addWaypoint</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~airspeedtype",
    "variable/index.html#static-variable-airspeedType",
    "<span>airspeedType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/sites.js~api",
    "variable/index.html#static-variable-api",
    "<span>api</span> <span class=\"search-result-import-path\">GCS/js/constants/Sites.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~armedtype",
    "variable/index.html#static-variable-armedType",
    "<span>armedType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~assertjson",
    "function/index.html#static-function-assertJson",
    "<span>assertJson</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~attitudetype",
    "variable/index.html#static-variable-attitudeType",
    "<span>attitudeType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~batterytype",
    "variable/index.html#static-variable-batteryType",
    "<span>batteryType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/sendapi.js~calibrationastart",
    "function/index.html#static-function-calibrationAStart",
    "<span>calibrationAStart</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~calibrationcontinue",
    "function/index.html#static-function-calibrationContinue",
    "<span>calibrationContinue</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~calibrationgstart",
    "function/index.html#static-function-calibrationGStart",
    "<span>calibrationGStart</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~calibrationpstart",
    "function/index.html#static-function-calibrationPStart",
    "<span>calibrationPStart</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~calibrationrcstart",
    "function/index.html#static-function-calibrationRCStart",
    "<span>calibrationRCStart</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~calibrationrcstop",
    "function/index.html#static-function-calibrationRCStop",
    "<span>calibrationRCStop</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/calibrationstore.js~calibrationstoreinstance",
    "variable/index.html#static-variable-calibrationStoreInstance",
    "<span>calibrationStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/CalibrationStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~cellchange",
    "function/index.html#static-function-cellChange",
    "<span>cellChange</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/settingsactioncreator.js~changehistoricalslider",
    "function/index.html#static-function-changeHistoricalSlider",
    "<span>changeHistoricalSlider</span> <span class=\"search-result-import-path\">GCS/js/actions/SettingsActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~changelocation",
    "function/index.html#static-function-changeLocation",
    "<span>changeLocation</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/calibrationactioncreator.js~clearcalibrationlines",
    "function/index.html#static-function-clearCalibrationLines",
    "<span>clearCalibrationLines</span> <span class=\"search-result-import-path\">GCS/js/actions/CalibrationActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~clicksection",
    "function/index.html#static-function-clickSection",
    "<span>clickSection</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~climbratetype",
    "variable/index.html#static-variable-climbRateType",
    "<span>climbRateType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/componentutils.js~colortobutton",
    "function/index.html#static-function-colorToButton",
    "<span>colorToButton</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/configdata.js~confignames",
    "variable/index.html#static-variable-configNames",
    "<span>configNames</span> <span class=\"search-result-import-path\">GCS/js/utils/ConfigData.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/configdata.js~confirmobj",
    "function/index.html#static-function-confirmObj",
    "<span>confirmObj</span> <span class=\"search-result-import-path\">GCS/js/utils/ConfigData.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~confirmselect",
    "function/index.html#static-function-confirmSelect",
    "<span>confirmSelect</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~confirmselectmap",
    "function/index.html#static-function-confirmSelectMap",
    "<span>confirmSelectMap</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~currentwaypointtype",
    "variable/index.html#static-variable-currentWaypointType",
    "<span>currentWaypointType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/componentutils.js~datetostring",
    "function/index.html#static-function-dateToString",
    "<span>dateToString</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~decround",
    "function/index.html#static-function-decround",
    "<span>decround</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~deleteallwaypoints",
    "function/index.html#static-function-deleteAllWaypoints",
    "<span>deleteAllWaypoints</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~deletewp",
    "function/index.html#static-function-deleteWP",
    "<span>deleteWP</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~deletewaypoint",
    "function/index.html#static-function-deleteWaypoint",
    "<span>deleteWaypoint</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~disconnect",
    "function/index.html#static-function-disconnect",
    "<span>disconnect</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~editparameter",
    "function/index.html#static-function-editParameter",
    "<span>editParameter</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~enabledtosuccess",
    "function/index.html#static-function-enabledToSuccess",
    "<span>enabledToSuccess</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/fencestore.js~fencestoreinstance",
    "variable/index.html#static-variable-fenceStoreInstance",
    "<span>fenceStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/FenceStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~fencetype",
    "variable/index.html#static-variable-fenceType",
    "<span>fenceType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/componentutils.js~fttom",
    "function/index.html#static-function-ftToM",
    "<span>ftToM</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/configdata.js~getconfigvalue",
    "function/index.html#static-function-getConfigValue",
    "<span>getConfigValue</span> <span class=\"search-result-import-path\">GCS/js/utils/ConfigData.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/receiveapi.js~gethistoricaldata",
    "function/index.html#static-function-getHistoricalData",
    "<span>getHistoricalData</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/receiveapi.js~getlocations",
    "function/index.html#static-function-getLocations",
    "<span>getLocations</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~gpstype",
    "variable/index.html#static-variable-gpsType",
    "<span>gpsType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/receiveapi.js~haltreceiveloop",
    "function/index.html#static-function-haltReceiveLoop",
    "<span>haltReceiveLoop</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/receiveapi.js~initializeinterop",
    "function/index.html#static-function-initializeInterop",
    "<span>initializeInterop</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~initializemap",
    "function/index.html#static-function-initializeMap",
    "<span>initializeMap</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/receiveapi.js~initializeparameters",
    "function/index.html#static-function-initializeParameters",
    "<span>initializeParameters</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/interopstore.js~interopstoreinstance",
    "variable/index.html#static-variable-interopStoreInstance",
    "<span>interopStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/InteropStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~linktype",
    "variable/index.html#static-variable-linkType",
    "<span>linkType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/loadapi.js~loadfencefromfile",
    "function/index.html#static-function-loadFenceFromFile",
    "<span>loadFenceFromFile</span> <span class=\"search-result-import-path\">GCS/js/utils/LoadApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~loadparametersfromfile",
    "function/index.html#static-function-loadParametersFromFile",
    "<span>loadParametersFromFile</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/loadapi.js~loadparamsfromfile",
    "function/index.html#static-function-loadParamsFromFile",
    "<span>loadParamsFromFile</span> <span class=\"search-result-import-path\">GCS/js/utils/LoadApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~loadwaypointsfromfile",
    "function/index.html#static-function-loadWaypointsFromFile",
    "<span>loadWaypointsFromFile</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/loadapi.js~loadwaypointsfromfile",
    "function/index.html#static-function-loadWaypointsFromFile",
    "<span>loadWaypointsFromFile</span> <span class=\"search-result-import-path\">GCS/js/utils/LoadApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/tuningactioncreator.js~lockvalue",
    "function/index.html#static-function-lockValue",
    "<span>lockValue</span> <span class=\"search-result-import-path\">GCS/js/actions/TuningActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~mtoft",
    "function/index.html#static-function-mToFt",
    "<span>mToFt</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~m_stoknots",
    "function/index.html#static-function-m_sToKnots",
    "<span>m_sToKnots</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~mapresize",
    "function/index.html#static-function-mapResize",
    "<span>mapResize</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~modetype",
    "variable/index.html#static-variable-modeType",
    "<span>modeType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/actions/tuningactioncreator.js~nexttuningflight",
    "function/index.html#static-function-nextTuningFlight",
    "<span>nextTuningFlight</span> <span class=\"search-result-import-path\">GCS/js/actions/TuningActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/parametersstore.js~parametersstoreinstance",
    "variable/index.html#static-variable-parametersStoreInstance",
    "<span>parametersStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/ParametersStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/paramdocumentation.js~params",
    "variable/index.html#static-variable-params",
    "<span>params</span> <span class=\"search-result-import-path\">GCS/js/utils/ParamDocumentation.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~powerboardtype",
    "variable/index.html#static-variable-powerboardType",
    "<span>powerboardType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/actions/tuningactioncreator.js~prevtuningflight",
    "function/index.html#static-function-prevTuningFlight",
    "<span>prevTuningFlight</span> <span class=\"search-result-import-path\">GCS/js/actions/TuningActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~pythagorean",
    "function/index.html#static-function-pythagorean",
    "<span>pythagorean</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~reboot",
    "function/index.html#static-function-reboot",
    "<span>reboot</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receiveairspeed",
    "function/index.html#static-function-receiveAirspeed",
    "<span>receiveAirspeed</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivearmed",
    "function/index.html#static-function-receiveArmed",
    "<span>receiveArmed</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receiveattitude",
    "function/index.html#static-function-receiveAttitude",
    "<span>receiveAttitude</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivebattery",
    "function/index.html#static-function-receiveBattery",
    "<span>receiveBattery</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receiveclimbrate",
    "function/index.html#static-function-receiveClimbRate",
    "<span>receiveClimbRate</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~receivecurrent",
    "function/index.html#static-function-receiveCurrent",
    "<span>receiveCurrent</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivecurrentmode",
    "function/index.html#static-function-receiveCurrentMode",
    "<span>receiveCurrentMode</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/fenceactioncreator.js~receivefencepoints",
    "function/index.html#static-function-receiveFencePoints",
    "<span>receiveFencePoints</span> <span class=\"search-result-import-path\">GCS/js/actions/FenceActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/fenceactioncreator.js~receivefencesenabled",
    "function/index.html#static-function-receiveFencesEnabled",
    "<span>receiveFencesEnabled</span> <span class=\"search-result-import-path\">GCS/js/actions/FenceActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/settingsactioncreator.js~receiveflightnotes",
    "function/index.html#static-function-receiveFlightNotes",
    "<span>receiveFlightNotes</span> <span class=\"search-result-import-path\">GCS/js/actions/SettingsActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivegps",
    "function/index.html#static-function-receiveGPS",
    "<span>receiveGPS</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivegpslink",
    "function/index.html#static-function-receiveGPSLink",
    "<span>receiveGPSLink</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/interopactioncreator.js~receiveinteropactive",
    "function/index.html#static-function-receiveInteropActive",
    "<span>receiveInteropActive</span> <span class=\"search-result-import-path\">GCS/js/actions/InteropActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/interopactioncreator.js~receiveinteropalive",
    "function/index.html#static-function-receiveInteropAlive",
    "<span>receiveInteropAlive</span> <span class=\"search-result-import-path\">GCS/js/actions/InteropActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/settingsactioncreator.js~receivelocation",
    "function/index.html#static-function-receiveLocation",
    "<span>receiveLocation</span> <span class=\"search-result-import-path\">GCS/js/actions/SettingsActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/settingsactioncreator.js~receivelocations",
    "function/index.html#static-function-receiveLocations",
    "<span>receiveLocations</span> <span class=\"search-result-import-path\">GCS/js/actions/SettingsActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~receivemaxparamcount",
    "function/index.html#static-function-receiveMaxParamCount",
    "<span>receiveMaxParamCount</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~receivemodalopen",
    "function/index.html#static-function-receiveModalOpen",
    "<span>receiveModalOpen</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivemodeswitch",
    "function/index.html#static-function-receiveModeSwitch",
    "<span>receiveModeSwitch</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~receivemultipleparameters",
    "function/index.html#static-function-receiveMultipleParameters",
    "<span>receiveMultipleParameters</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~receivenote",
    "function/index.html#static-function-receiveNote",
    "<span>receiveNote</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/interopactioncreator.js~receiveobstacles",
    "function/index.html#static-function-receiveObstacles",
    "<span>receiveObstacles</span> <span class=\"search-result-import-path\">GCS/js/actions/InteropActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/interopactioncreator.js~receiveoffaxis",
    "function/index.html#static-function-receiveOffAxis",
    "<span>receiveOffAxis</span> <span class=\"search-result-import-path\">GCS/js/actions/InteropActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receiveplanelink",
    "function/index.html#static-function-receivePlaneLink",
    "<span>receivePlaneLink</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivepowerboard",
    "function/index.html#static-function-receivePowerboard",
    "<span>receivePowerboard</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivesafetyswitch",
    "function/index.html#static-function-receiveSafetySwitch",
    "<span>receiveSafetySwitch</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/sdaactioncreator.js~receivesdaenabled",
    "function/index.html#static-function-receiveSdaEnabled",
    "<span>receiveSdaEnabled</span> <span class=\"search-result-import-path\">GCS/js/actions/SdaActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~receivesearchfield",
    "function/index.html#static-function-receiveSearchField",
    "<span>receiveSearchField</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~receivesingleparameter",
    "function/index.html#static-function-receiveSingleParameter",
    "<span>receiveSingleParameter</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivethrottle",
    "function/index.html#static-function-receiveThrottle",
    "<span>receiveThrottle</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~receivewaypoints",
    "function/index.html#static-function-receiveWaypoints",
    "<span>receiveWaypoints</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~receivewind",
    "function/index.html#static-function-receiveWind",
    "<span>receiveWind</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/statusactioncreator.js~reconnect",
    "function/index.html#static-function-reconnect",
    "<span>reconnect</span> <span class=\"search-result-import-path\">GCS/js/actions/StatusActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~redrawfence",
    "function/index.html#static-function-redrawFence",
    "<span>redrawFence</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~redrawobstacles",
    "function/index.html#static-function-redrawObstacles",
    "<span>redrawObstacles</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~redrawoffaxis",
    "function/index.html#static-function-redrawOffAxis",
    "<span>redrawOffAxis</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~redrawplane",
    "function/index.html#static-function-redrawPlane",
    "<span>redrawPlane</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~redrawwaypoints",
    "function/index.html#static-function-redrawWaypoints",
    "<span>redrawWaypoints</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~resetplanepath",
    "function/index.html#static-function-resetPlanePath",
    "<span>resetPlanePath</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/tuningactioncreator.js~resettuning",
    "function/index.html#static-function-resetTuning",
    "<span>resetTuning</span> <span class=\"search-result-import-path\">GCS/js/actions/TuningActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/receiveapi.js~resumereceiveloop",
    "function/index.html#static-function-resumeReceiveLoop",
    "<span>resumeReceiveLoop</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~safetyswitchtype",
    "variable/index.html#static-variable-safetySwitchType",
    "<span>safetySwitchType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/downloadapi.js~savefencetofile",
    "function/index.html#static-function-saveFenceToFile",
    "<span>saveFenceToFile</span> <span class=\"search-result-import-path\">GCS/js/utils/DownloadApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~saveparammodal",
    "function/index.html#static-function-saveParamModal",
    "<span>saveParamModal</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/downloadapi.js~saveparamstofile",
    "function/index.html#static-function-saveParamsToFile",
    "<span>saveParamsToFile</span> <span class=\"search-result-import-path\">GCS/js/utils/DownloadApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/downloadapi.js~savewaypointstofile",
    "function/index.html#static-function-saveWaypointsToFile",
    "<span>saveWaypointsToFile</span> <span class=\"search-result-import-path\">GCS/js/utils/DownloadApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/downloadapi.js~savewaypointstojson",
    "function/index.html#static-function-saveWaypointsToJson",
    "<span>saveWaypointsToJson</span> <span class=\"search-result-import-path\">GCS/js/utils/DownloadApi.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/sdastore.js~sdastoreinstance",
    "variable/index.html#static-variable-sdaStoreInstance",
    "<span>sdaStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/SdaStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~sdatype",
    "variable/index.html#static-variable-sdaType",
    "<span>sdaType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/actions/parametersactioncreator.js~selectparameter",
    "function/index.html#static-function-selectParameter",
    "<span>selectParameter</span> <span class=\"search-result-import-path\">GCS/js/actions/ParametersActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendallparameters",
    "function/index.html#static-function-sendAllParameters",
    "<span>sendAllParameters</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendchangemode",
    "function/index.html#static-function-sendChangeMode",
    "<span>sendChangeMode</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendgeofencepoints",
    "function/index.html#static-function-sendGeofencePoints",
    "<span>sendGeofencePoints</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendmodeswitch",
    "function/index.html#static-function-sendModeSwitch",
    "<span>sendModeSwitch</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendparameter",
    "function/index.html#static-function-sendParameter",
    "<span>sendParameter</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendrtl",
    "function/index.html#static-function-sendRTL",
    "<span>sendRTL</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~sendwaypoint",
    "function/index.html#static-function-sendWaypoint",
    "<span>sendWaypoint</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendwaypoint",
    "function/index.html#static-function-sendWaypoint",
    "<span>sendWaypoint</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~sendwaypointlist",
    "function/index.html#static-function-sendWaypointList",
    "<span>sendWaypointList</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/configdata.js~setconfigvalue",
    "function/index.html#static-function-setConfigValue",
    "<span>setConfigValue</span> <span class=\"search-result-import-path\">GCS/js/utils/ConfigData.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~setcurrent",
    "function/index.html#static-function-setCurrent",
    "<span>setCurrent</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~setcurrentwp",
    "function/index.html#static-function-setCurrentWP",
    "<span>setCurrentWP</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~setselected",
    "function/index.html#static-function-setSelected",
    "<span>setSelected</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/settingsstore.js~settingsstoreinstance",
    "variable/index.html#static-variable-settingsStoreInstance",
    "<span>settingsStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/SettingsStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/constants/sites.js~site",
    "variable/index.html#static-variable-site",
    "<span>site</span> <span class=\"search-result-import-path\">GCS/js/constants/Sites.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/receiveapi.js~startinteropreceive",
    "function/index.html#static-function-startInteropReceive",
    "<span>startInteropReceive</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/receiveapi.js~startplanereceive",
    "function/index.html#static-function-startPlaneReceive",
    "<span>startPlaneReceive</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/statusstore.js~statusstoreinstance",
    "variable/index.html#static-variable-statusStoreInstance",
    "<span>statusStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/StatusStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/receiveapi.js~stopinteropreceive",
    "function/index.html#static-function-stopInteropReceive",
    "<span>stopInteropReceive</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/receiveapi.js~stopplanereceive",
    "function/index.html#static-function-stopPlaneReceive",
    "<span>stopPlaneReceive</span> <span class=\"search-result-import-path\">GCS/js/utils/ReceiveApi.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~throttletype",
    "variable/index.html#static-variable-throttleType",
    "<span>throttleType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/utils/sendapi.js~togglearm",
    "function/index.html#static-function-toggleArm",
    "<span>toggleArm</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~toggleinterop",
    "function/index.html#static-function-toggleInterop",
    "<span>toggleInterop</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~togglesda",
    "function/index.html#static-function-toggleSda",
    "<span>toggleSda</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/configdata.js~tokenobj",
    "function/index.html#static-function-tokenObj",
    "<span>tokenObj</span> <span class=\"search-result-import-path\">GCS/js/utils/ConfigData.js</span>",
    "function"
  ],
  [
    "gcs/js/stores/tuningstore.js~tuningstoreinstance",
    "variable/index.html#static-variable-tuningStoreInstance",
    "<span>tuningStoreInstance</span> <span class=\"search-result-import-path\">GCS/js/stores/TuningStore.js</span>",
    "variable"
  ],
  [
    "gcs/js/actions/settingsactioncreator.js~unitswitch",
    "function/index.html#static-function-unitSwitch",
    "<span>unitSwitch</span> <span class=\"search-result-import-path\">GCS/js/actions/SettingsActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~updatecelllatlon",
    "function/index.html#static-function-updateCellLatLon",
    "<span>updateCellLatLon</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/waypointactioncreator.js~updateitem",
    "function/index.html#static-function-updateItem",
    "<span>updateItem</span> <span class=\"search-result-import-path\">GCS/js/actions/WaypointActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/maputils.js~updatelocations",
    "function/index.html#static-function-updateLocations",
    "<span>updateLocations</span> <span class=\"search-result-import-path\">GCS/js/utils/MapUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/actions/tuningactioncreator.js~updatevalue",
    "function/index.html#static-function-updateValue",
    "<span>updateValue</span> <span class=\"search-result-import-path\">GCS/js/actions/TuningActionCreator.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/sendapi.js~updatewp",
    "function/index.html#static-function-updateWP",
    "<span>updateWP</span> <span class=\"search-result-import-path\">GCS/js/utils/SendApi.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~valueclose",
    "function/index.html#static-function-valueClose",
    "<span>valueClose</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~valuetocolor",
    "function/index.html#static-function-valueToColor",
    "<span>valueToColor</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~valuetocolorname",
    "function/index.html#static-function-valueToColorName",
    "<span>valueToColorName</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/utils/componentutils.js~valuetopercent",
    "function/index.html#static-function-valueToPercent",
    "<span>valueToPercent</span> <span class=\"search-result-import-path\">GCS/js/utils/ComponentUtils.js</span>",
    "function"
  ],
  [
    "gcs/js/interfaces/types.js~waypointstype",
    "variable/index.html#static-variable-waypointsType",
    "<span>waypointsType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "gcs/js/interfaces/types.js~windtype",
    "variable/index.html#static-variable-windType",
    "<span>windType</span> <span class=\"search-result-import-path\">GCS/js/interfaces/types.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "js/actions/calibrationactioncreator.js",
    "file/js/actions/CalibrationActionCreator.js.html",
    "js/actions/CalibrationActionCreator.js",
    "file"
  ],
  [
    "js/actions/fenceactioncreator.js",
    "file/js/actions/FenceActionCreator.js.html",
    "js/actions/FenceActionCreator.js",
    "file"
  ],
  [
    "js/actions/interopactioncreator.js",
    "file/js/actions/InteropActionCreator.js.html",
    "js/actions/InteropActionCreator.js",
    "file"
  ],
  [
    "js/actions/parametersactioncreator.js",
    "file/js/actions/ParametersActionCreator.js.html",
    "js/actions/ParametersActionCreator.js",
    "file"
  ],
  [
    "js/actions/sdaactioncreator.js",
    "file/js/actions/SdaActionCreator.js.html",
    "js/actions/SdaActionCreator.js",
    "file"
  ],
  [
    "js/actions/settingsactioncreator.js",
    "file/js/actions/SettingsActionCreator.js.html",
    "js/actions/SettingsActionCreator.js",
    "file"
  ],
  [
    "js/actions/statusactioncreator.js",
    "file/js/actions/StatusActionCreator.js.html",
    "js/actions/StatusActionCreator.js",
    "file"
  ],
  [
    "js/actions/tuningactioncreator.js",
    "file/js/actions/TuningActionCreator.js.html",
    "js/actions/TuningActionCreator.js",
    "file"
  ],
  [
    "js/actions/waypointactioncreator.js",
    "file/js/actions/WaypointActionCreator.js.html",
    "js/actions/WaypointActionCreator.js",
    "file"
  ],
  [
    "js/app.js",
    "file/js/app.js.html",
    "js/app.js",
    "file"
  ],
  [
    "js/constants/actiontypes.js",
    "file/js/constants/ActionTypes.js.html",
    "js/constants/ActionTypes.js",
    "file"
  ],
  [
    "js/constants/buttontypes.js",
    "file/js/constants/ButtonTypes.js.html",
    "js/constants/ButtonTypes.js",
    "file"
  ],
  [
    "js/constants/frequency.js",
    "file/js/constants/Frequency.js.html",
    "js/constants/Frequency.js",
    "file"
  ],
  [
    "js/constants/sites.js",
    "file/js/constants/Sites.js.html",
    "js/constants/Sites.js",
    "file"
  ],
  [
    "js/dispatcher/gcsdispatcher.js",
    "file/js/dispatcher/GCSDispatcher.js.html",
    "js/dispatcher/GCSDispatcher.js",
    "file"
  ],
  [
    "js/interfaces/components.js",
    "file/js/interfaces/components.js.html",
    "js/interfaces/components.js",
    "file"
  ],
  [
    "js/interfaces/components.js~displayinfotype",
    "typedef/index.html#static-typedef-DisplayInfoType",
    "js/interfaces/components.js~DisplayInfoType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~dropdownoptiontype",
    "typedef/index.html#static-typedef-DropdownOptionType",
    "js/interfaces/components.js~DropdownOptionType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~flightnotestype",
    "typedef/index.html#static-typedef-FlightNotesType",
    "js/interfaces/components.js~FlightNotesType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~fullwidthbuttontype",
    "typedef/index.html#static-typedef-FullWidthButtonType",
    "js/interfaces/components.js~FullWidthButtonType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~fullwidthelementtype",
    "typedef/index.html#static-typedef-FullWidthElementType",
    "js/interfaces/components.js~FullWidthElementType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~fullwidthtextinputtype",
    "typedef/index.html#static-typedef-FullWidthTextInputType",
    "js/interfaces/components.js~FullWidthTextInputType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~modeoptiontype",
    "typedef/index.html#static-typedef-ModeOptionType",
    "js/interfaces/components.js~ModeOptionType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~navbarstatustype",
    "typedef/index.html#static-typedef-NavbarStatusType",
    "js/interfaces/components.js~NavbarStatusType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~planemodetype",
    "typedef/index.html#static-typedef-PlaneModeType",
    "js/interfaces/components.js~PlaneModeType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~settingsbuttontype",
    "typedef/index.html#static-typedef-SettingsButtonType",
    "js/interfaces/components.js~SettingsButtonType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~settingscheckboxtype",
    "typedef/index.html#static-typedef-SettingsCheckboxType",
    "js/interfaces/components.js~SettingsCheckboxType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~settingsdropdowntype",
    "typedef/index.html#static-typedef-SettingsDropdownType",
    "js/interfaces/components.js~SettingsDropdownType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~settingsitemtype",
    "typedef/index.html#static-typedef-SettingsItemType",
    "js/interfaces/components.js~SettingsItemType",
    "typedef"
  ],
  [
    "js/interfaces/components.js~settingstexttype",
    "typedef/index.html#static-typedef-SettingsTextType",
    "js/interfaces/components.js~SettingsTextType",
    "typedef"
  ],
  [
    "js/interfaces/external.js",
    "file/js/interfaces/external.js.html",
    "js/interfaces/external.js",
    "file"
  ],
  [
    "js/interfaces/typedefs.js",
    "file/js/interfaces/typedefs.js.html",
    "js/interfaces/typedefs.js",
    "file"
  ],
  [
    "js/interfaces/typedefs.js~airspeed",
    "typedef/index.html#static-typedef-Airspeed",
    "js/interfaces/typedefs.js~Airspeed",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~attitude",
    "typedef/index.html#static-typedef-Attitude",
    "js/interfaces/typedefs.js~Attitude",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~battery",
    "typedef/index.html#static-typedef-Battery",
    "js/interfaces/typedefs.js~Battery",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~cylinder",
    "typedef/index.html#static-typedef-Cylinder",
    "js/interfaces/typedefs.js~Cylinder",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~fullparameter",
    "typedef/index.html#static-typedef-FullParameter",
    "js/interfaces/typedefs.js~FullParameter",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~gps",
    "typedef/index.html#static-typedef-GPS",
    "js/interfaces/typedefs.js~GPS",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~nvalue",
    "typedef/index.html#static-typedef-NValue",
    "js/interfaces/typedefs.js~NValue",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~obstacle",
    "typedef/index.html#static-typedef-Obstacle",
    "js/interfaces/typedefs.js~Obstacle",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~obstaclelist",
    "typedef/index.html#static-typedef-ObstacleList",
    "js/interfaces/typedefs.js~ObstacleList",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~parameter",
    "typedef/index.html#static-typedef-Parameter",
    "js/interfaces/typedefs.js~Parameter",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~point",
    "typedef/index.html#static-typedef-Point",
    "js/interfaces/typedefs.js~Point",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~powerboard",
    "typedef/index.html#static-typedef-Powerboard",
    "js/interfaces/typedefs.js~Powerboard",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~sphere",
    "typedef/index.html#static-typedef-Sphere",
    "js/interfaces/typedefs.js~Sphere",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~waypoint",
    "typedef/index.html#static-typedef-Waypoint",
    "js/interfaces/typedefs.js~Waypoint",
    "typedef"
  ],
  [
    "js/interfaces/typedefs.js~wind",
    "typedef/index.html#static-typedef-Wind",
    "js/interfaces/typedefs.js~Wind",
    "typedef"
  ],
  [
    "js/interfaces/types.js",
    "file/js/interfaces/types.js.html",
    "js/interfaces/types.js",
    "file"
  ],
  [
    "js/stores/calibrationstore.js",
    "file/js/stores/CalibrationStore.js.html",
    "js/stores/CalibrationStore.js",
    "file"
  ],
  [
    "js/stores/calibrationstore.js~calibrationstore#constructor",
    "class/js/stores/CalibrationStore.js~CalibrationStore.html#instance-constructor-constructor",
    "js/stores/CalibrationStore.js~CalibrationStore#constructor",
    "method"
  ],
  [
    "js/stores/calibrationstore.js~calibrationstore#getcontrols",
    "class/js/stores/CalibrationStore.js~CalibrationStore.html#instance-method-getControls",
    "js/stores/CalibrationStore.js~CalibrationStore#getControls",
    "method"
  ],
  [
    "js/stores/calibrationstore.js~calibrationstore#getlines",
    "class/js/stores/CalibrationStore.js~CalibrationStore.html#instance-method-getLines",
    "js/stores/CalibrationStore.js~CalibrationStore#getLines",
    "method"
  ],
  [
    "js/stores/fencestore.js",
    "file/js/stores/FenceStore.js.html",
    "js/stores/FenceStore.js",
    "file"
  ],
  [
    "js/stores/fencestore.js~fencestore#constructor",
    "class/js/stores/FenceStore.js~FenceStore.html#instance-constructor-constructor",
    "js/stores/FenceStore.js~FenceStore#constructor",
    "method"
  ],
  [
    "js/stores/fencestore.js~fencestore#getbuttons",
    "class/js/stores/FenceStore.js~FenceStore.html#instance-method-getButtons",
    "js/stores/FenceStore.js~FenceStore#getButtons",
    "method"
  ],
  [
    "js/stores/fencestore.js~fencestore#getfencepoints",
    "class/js/stores/FenceStore.js~FenceStore.html#instance-method-getFencePoints",
    "js/stores/FenceStore.js~FenceStore#getFencePoints",
    "method"
  ],
  [
    "js/stores/fencestore.js~fencestore#getfencesenabled",
    "class/js/stores/FenceStore.js~FenceStore.html#instance-method-getFencesEnabled",
    "js/stores/FenceStore.js~FenceStore#getFencesEnabled",
    "method"
  ],
  [
    "js/stores/interopstore.js",
    "file/js/stores/InteropStore.js.html",
    "js/stores/InteropStore.js",
    "file"
  ],
  [
    "js/stores/interopstore.js~interopstore#constructor",
    "class/js/stores/InteropStore.js~InteropStore.html#instance-constructor-constructor",
    "js/stores/InteropStore.js~InteropStore#constructor",
    "method"
  ],
  [
    "js/stores/interopstore.js~interopstore#getcontrols",
    "class/js/stores/InteropStore.js~InteropStore.html#instance-method-getControls",
    "js/stores/InteropStore.js~InteropStore#getControls",
    "method"
  ],
  [
    "js/stores/interopstore.js~interopstore#getgonogo",
    "class/js/stores/InteropStore.js~InteropStore.html#instance-method-getGoNoGo",
    "js/stores/InteropStore.js~InteropStore#getGoNoGo",
    "method"
  ],
  [
    "js/stores/interopstore.js~interopstore#getinteropactive",
    "class/js/stores/InteropStore.js~InteropStore.html#instance-method-getInteropActive",
    "js/stores/InteropStore.js~InteropStore#getInteropActive",
    "method"
  ],
  [
    "js/stores/interopstore.js~interopstore#getinteropalive",
    "class/js/stores/InteropStore.js~InteropStore.html#instance-method-getInteropAlive",
    "js/stores/InteropStore.js~InteropStore#getInteropAlive",
    "method"
  ],
  [
    "js/stores/interopstore.js~interopstore#getobstacles",
    "class/js/stores/InteropStore.js~InteropStore.html#instance-method-getObstacles",
    "js/stores/InteropStore.js~InteropStore#getObstacles",
    "method"
  ],
  [
    "js/stores/interopstore.js~interopstore#getoffaxis",
    "class/js/stores/InteropStore.js~InteropStore.html#instance-method-getOffAxis",
    "js/stores/InteropStore.js~InteropStore#getOffAxis",
    "method"
  ],
  [
    "js/stores/parametersstore.js",
    "file/js/stores/ParametersStore.js.html",
    "js/stores/ParametersStore.js",
    "file"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#constructor",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-constructor-constructor",
    "js/stores/ParametersStore.js~ParametersStore#constructor",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getdiff",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getDiff",
    "js/stores/ParametersStore.js~ParametersStore#getDiff",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getgonogo",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getGoNoGo",
    "js/stores/ParametersStore.js~ParametersStore#getGoNoGo",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getmodalopen",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getModalOpen",
    "js/stores/ParametersStore.js~ParametersStore#getModalOpen",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getparametercontrols",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getParameterControls",
    "js/stores/ParametersStore.js~ParametersStore#getParameterControls",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getparametermap",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getParameterMap",
    "js/stores/ParametersStore.js~ParametersStore#getParameterMap",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getparameters",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getParameters",
    "js/stores/ParametersStore.js~ParametersStore#getParameters",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getprogress",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getProgress",
    "js/stores/ParametersStore.js~ParametersStore#getProgress",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getsearchedparameters",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getSearchedParameters",
    "js/stores/ParametersStore.js~ParametersStore#getSearchedParameters",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getselected",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getSelected",
    "js/stores/ParametersStore.js~ParametersStore#getSelected",
    "method"
  ],
  [
    "js/stores/parametersstore.js~parametersstore#getselectedparameter",
    "class/js/stores/ParametersStore.js~ParametersStore.html#instance-method-getSelectedParameter",
    "js/stores/ParametersStore.js~ParametersStore#getSelectedParameter",
    "method"
  ],
  [
    "js/stores/sdastore.js",
    "file/js/stores/SdaStore.js.html",
    "js/stores/SdaStore.js",
    "file"
  ],
  [
    "js/stores/sdastore.js~sdastore#constructor",
    "class/js/stores/SdaStore.js~SdaStore.html#instance-constructor-constructor",
    "js/stores/SdaStore.js~SdaStore#constructor",
    "method"
  ],
  [
    "js/stores/sdastore.js~sdastore#getcontrols",
    "class/js/stores/SdaStore.js~SdaStore.html#instance-method-getControls",
    "js/stores/SdaStore.js~SdaStore#getControls",
    "method"
  ],
  [
    "js/stores/sdastore.js~sdastore#getsdastatus",
    "class/js/stores/SdaStore.js~SdaStore.html#instance-method-getSdaStatus",
    "js/stores/SdaStore.js~SdaStore#getSdaStatus",
    "method"
  ],
  [
    "js/stores/settingsstore.js",
    "file/js/stores/SettingsStore.js.html",
    "js/stores/SettingsStore.js",
    "file"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#constructor",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-constructor-constructor",
    "js/stores/SettingsStore.js~SettingsStore#constructor",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#getcritical",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getCritical",
    "js/stores/SettingsStore.js~SettingsStore#getCritical",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#getflightnotes",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getFlightNotes",
    "js/stores/SettingsStore.js~SettingsStore#getFlightNotes",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#gethistoricalslider",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getHistoricalSlider",
    "js/stores/SettingsStore.js~SettingsStore#getHistoricalSlider",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#getlocation",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getLocation",
    "js/stores/SettingsStore.js~SettingsStore#getLocation",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#getlocations",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getLocations",
    "js/stores/SettingsStore.js~SettingsStore#getLocations",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#getsettings",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getSettings",
    "js/stores/SettingsStore.js~SettingsStore#getSettings",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#getslideronchange",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getSliderOnChange",
    "js/stores/SettingsStore.js~SettingsStore#getSliderOnChange",
    "method"
  ],
  [
    "js/stores/settingsstore.js~settingsstore#getunitswitch",
    "class/js/stores/SettingsStore.js~SettingsStore.html#instance-method-getUnitSwitch",
    "js/stores/SettingsStore.js~SettingsStore#getUnitSwitch",
    "method"
  ],
  [
    "js/stores/statusstore.js",
    "file/js/stores/StatusStore.js.html",
    "js/stores/StatusStore.js",
    "file"
  ],
  [
    "js/stores/statusstore.js~statusstore#constructor",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-constructor-constructor",
    "js/stores/StatusStore.js~StatusStore#constructor",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getairspeed",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getAirspeed",
    "js/stores/StatusStore.js~StatusStore#getAirspeed",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getarmed",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getArmed",
    "js/stores/StatusStore.js~StatusStore#getArmed",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getbattery",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getBattery",
    "js/stores/StatusStore.js~StatusStore#getBattery",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getconnected",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getConnected",
    "js/stores/StatusStore.js~StatusStore#getConnected",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getcontrols",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getControls",
    "js/stores/StatusStore.js~StatusStore#getControls",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getgps",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getGPS",
    "js/stores/StatusStore.js~StatusStore#getGPS",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getgonogo",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getGoNoGo",
    "js/stores/StatusStore.js~StatusStore#getGoNoGo",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getmode",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getMode",
    "js/stores/StatusStore.js~StatusStore#getMode",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getplaneinfo",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getPlaneInfo",
    "js/stores/StatusStore.js~StatusStore#getPlaneInfo",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getplanemodes",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getPlaneModes",
    "js/stores/StatusStore.js~StatusStore#getPlaneModes",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getplanestatus",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getPlaneStatus",
    "js/stores/StatusStore.js~StatusStore#getPlaneStatus",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getplanevalues",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getPlaneValues",
    "js/stores/StatusStore.js~StatusStore#getPlaneValues",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getpowerboard",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getPowerboard",
    "js/stores/StatusStore.js~StatusStore#getPowerboard",
    "method"
  ],
  [
    "js/stores/statusstore.js~statusstore#getthrottle100",
    "class/js/stores/StatusStore.js~StatusStore.html#instance-method-getThrottle100",
    "js/stores/StatusStore.js~StatusStore#getThrottle100",
    "method"
  ],
  [
    "js/stores/store.js",
    "file/js/stores/Store.js.html",
    "js/stores/Store.js",
    "file"
  ],
  [
    "js/stores/store.js~store#addchangelistener",
    "class/js/stores/Store.js~Store.html#instance-method-addChangeListener",
    "js/stores/Store.js~Store#addChangeListener",
    "method"
  ],
  [
    "js/stores/store.js~store#constructor",
    "class/js/stores/Store.js~Store.html#instance-constructor-constructor",
    "js/stores/Store.js~Store#constructor",
    "method"
  ],
  [
    "js/stores/store.js~store#emitchange",
    "class/js/stores/Store.js~Store.html#instance-method-emitChange",
    "js/stores/Store.js~Store#emitChange",
    "method"
  ],
  [
    "js/stores/store.js~store#removechangelistener",
    "class/js/stores/Store.js~Store.html#instance-method-removeChangeListener",
    "js/stores/Store.js~Store#removeChangeListener",
    "method"
  ],
  [
    "js/stores/tuningstore.js",
    "file/js/stores/TuningStore.js.html",
    "js/stores/TuningStore.js",
    "file"
  ],
  [
    "js/stores/tuningstore.js~tuningstore#constructor",
    "class/js/stores/TuningStore.js~TuningStore.html#instance-constructor-constructor",
    "js/stores/TuningStore.js~TuningStore#constructor",
    "method"
  ],
  [
    "js/stores/tuningstore.js~tuningstore#getallvalues",
    "class/js/stores/TuningStore.js~TuningStore.html#instance-method-getAllValues",
    "js/stores/TuningStore.js~TuningStore#getAllValues",
    "method"
  ],
  [
    "js/stores/tuningstore.js~tuningstore#getcurrentflight",
    "class/js/stores/TuningStore.js~TuningStore.html#instance-method-getCurrentFlight",
    "js/stores/TuningStore.js~TuningStore#getCurrentFlight",
    "method"
  ],
  [
    "js/stores/tuningstore.js~tuningstore#getflighttask",
    "class/js/stores/TuningStore.js~TuningStore.html#instance-method-getFlightTask",
    "js/stores/TuningStore.js~TuningStore#getFlightTask",
    "method"
  ],
  [
    "js/stores/tuningstore.js~tuningstore#getflightvalues",
    "class/js/stores/TuningStore.js~TuningStore.html#instance-method-getFlightValues",
    "js/stores/TuningStore.js~TuningStore#getFlightValues",
    "method"
  ],
  [
    "js/stores/tuningstore.js~tuningstore#getmaxflight",
    "class/js/stores/TuningStore.js~TuningStore.html#instance-method-getMaxFlight",
    "js/stores/TuningStore.js~TuningStore#getMaxFlight",
    "method"
  ],
  [
    "js/stores/waypointstore.js",
    "file/js/stores/WaypointStore.js.html",
    "js/stores/WaypointStore.js",
    "file"
  ],
  [
    "js/utils/componentutils.js",
    "file/js/utils/ComponentUtils.js.html",
    "js/utils/ComponentUtils.js",
    "file"
  ],
  [
    "js/utils/configdata.js",
    "file/js/utils/ConfigData.js.html",
    "js/utils/ConfigData.js",
    "file"
  ],
  [
    "js/utils/downloadapi.js",
    "file/js/utils/DownloadApi.js.html",
    "js/utils/DownloadApi.js",
    "file"
  ],
  [
    "js/utils/loadapi.js",
    "file/js/utils/LoadApi.js.html",
    "js/utils/LoadApi.js",
    "file"
  ],
  [
    "js/utils/maputils.js",
    "file/js/utils/MapUtils.js.html",
    "js/utils/MapUtils.js",
    "file"
  ],
  [
    "js/utils/paramdocumentation.js",
    "file/js/utils/ParamDocumentation.js.html",
    "js/utils/ParamDocumentation.js",
    "file"
  ],
  [
    "js/utils/receiveapi.js",
    "file/js/utils/ReceiveApi.js.html",
    "js/utils/ReceiveApi.js",
    "file"
  ],
  [
    "js/utils/sendapi.js",
    "file/js/utils/SendApi.js.html",
    "js/utils/SendApi.js",
    "file"
  ]
]